// GENERATED by scripts/generate-cover-srcset.py — do not edit by hand.
// Re-run that script after adding or replacing a cover.

export interface CoverVariant {
  w: number;
  src: string;
}

export interface CoverEntry {
  /** True intrinsic width of the referenced original. */
  width: number;
  height: number;
  variants: CoverVariant[];
}

export const COVER_MANIFEST: Record<string, CoverEntry> = {
  "/covers/book1-hardcover-v3.png": {
    "height": 3000,
    "variants": [
      {
        "src": "/covers/book1-hardcover-v3-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/book1-hardcover-v3-1320w.webp",
        "w": 1320
      },
      {
        "src": "/covers/book1-hardcover-v3-2000w.webp",
        "w": 2000
      }
    ],
    "width": 2000
  },
  "/covers/book1-paperback.png": {
    "height": 1500,
    "variants": [
      {
        "src": "/covers/book1-paperback-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/book1-paperback-1000w.webp",
        "w": 1000
      }
    ],
    "width": 1000
  },
  "/covers/book2-hardcover-v3.png": {
    "height": 3000,
    "variants": [
      {
        "src": "/covers/book2-hardcover-v3-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/book2-hardcover-v3-1320w.webp",
        "w": 1320
      },
      {
        "src": "/covers/book2-hardcover-v3-2000w.webp",
        "w": 2000
      }
    ],
    "width": 2000
  },
  "/covers/book2-paperback.png": {
    "height": 1500,
    "variants": [
      {
        "src": "/covers/book2-paperback-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/book2-paperback-1000w.webp",
        "w": 1000
      }
    ],
    "width": 1000
  },
  "/covers/book3-hardcover-v3.png": {
    "height": 3000,
    "variants": [
      {
        "src": "/covers/book3-hardcover-v3-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/book3-hardcover-v3-1320w.webp",
        "w": 1320
      },
      {
        "src": "/covers/book3-hardcover-v3-2000w.webp",
        "w": 2000
      }
    ],
    "width": 2000
  },
  "/covers/book3-paperback.png": {
    "height": 1500,
    "variants": [
      {
        "src": "/covers/book3-paperback-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/book3-paperback-1000w.webp",
        "w": 1000
      }
    ],
    "width": 1000
  },
  "/covers/omnibus-hardcover-v3.png": {
    "height": 3000,
    "variants": [
      {
        "src": "/covers/omnibus-hardcover-v3-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/omnibus-hardcover-v3-1320w.webp",
        "w": 1320
      },
      {
        "src": "/covers/omnibus-hardcover-v3-2000w.webp",
        "w": 2000
      }
    ],
    "width": 2000
  }
};
