// GENERATED by scripts/generate-cover-srcset.py — do not edit by hand.
// Re-run that script after adding or replacing a cover.

export interface CoverVariant {
  w: number;
  src: string;
}

export interface CoverEntry {
  /** True intrinsic width of the referenced original. */
  width: number;
  height: number;
  variants: CoverVariant[];
}

export const COVER_MANIFEST: Record<string, CoverEntry> = {
  "/covers/book1-case-cover.jpg": {
    "height": 3000,
    "variants": [
      {
        "src": "/covers/book1-case-cover-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/book1-case-cover-1320w.webp",
        "w": 1320
      },
      {
        "src": "/covers/book1-case-cover-2000w.webp",
        "w": 2000
      }
    ],
    "width": 2000
  },
  "/covers/book1-ebook.jpg": {
    "height": 2400,
    "variants": [
      {
        "src": "/covers/book1-ebook-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/book1-ebook-1320w.webp",
        "w": 1320
      },
      {
        "src": "/covers/book1-ebook-1600w.webp",
        "w": 1600
      }
    ],
    "width": 1600
  },
  "/covers/book1-hardcover-v3.png": {
    "height": 3000,
    "variants": [
      {
        "src": "/covers/book1-hardcover-v3-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/book1-hardcover-v3-1320w.webp",
        "w": 1320
      },
      {
        "src": "/covers/book1-hardcover-v3-2000w.webp",
        "w": 2000
      }
    ],
    "width": 2000
  },
  "/covers/book1-paperback.png": {
    "height": 1500,
    "variants": [
      {
        "src": "/covers/book1-paperback-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/book1-paperback-1000w.webp",
        "w": 1000
      }
    ],
    "width": 1000
  },
  "/covers/book2-case-cover.jpg": {
    "height": 3000,
    "variants": [
      {
        "src": "/covers/book2-case-cover-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/book2-case-cover-1320w.webp",
        "w": 1320
      },
      {
        "src": "/covers/book2-case-cover-2000w.webp",
        "w": 2000
      }
    ],
    "width": 2000
  },
  "/covers/book2-ebook.jpg": {
    "height": 2400,
    "variants": [
      {
        "src": "/covers/book2-ebook-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/book2-ebook-1320w.webp",
        "w": 1320
      },
      {
        "src": "/covers/book2-ebook-1600w.webp",
        "w": 1600
      }
    ],
    "width": 1600
  },
  "/covers/book2-hardcover-v3.png": {
    "height": 3000,
    "variants": [
      {
        "src": "/covers/book2-hardcover-v3-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/book2-hardcover-v3-1320w.webp",
        "w": 1320
      },
      {
        "src": "/covers/book2-hardcover-v3-2000w.webp",
        "w": 2000
      }
    ],
    "width": 2000
  },
  "/covers/book2-paperback.png": {
    "height": 1500,
    "variants": [
      {
        "src": "/covers/book2-paperback-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/book2-paperback-1000w.webp",
        "w": 1000
      }
    ],
    "width": 1000
  },
  "/covers/book3-case-cover.jpg": {
    "height": 3000,
    "variants": [
      {
        "src": "/covers/book3-case-cover-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/book3-case-cover-1320w.webp",
        "w": 1320
      },
      {
        "src": "/covers/book3-case-cover-2000w.webp",
        "w": 2000
      }
    ],
    "width": 2000
  },
  "/covers/book3-ebook.jpg": {
    "height": 2400,
    "variants": [
      {
        "src": "/covers/book3-ebook-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/book3-ebook-1320w.webp",
        "w": 1320
      },
      {
        "src": "/covers/book3-ebook-1600w.webp",
        "w": 1600
      }
    ],
    "width": 1600
  },
  "/covers/book3-hardcover-v3.png": {
    "height": 3000,
    "variants": [
      {
        "src": "/covers/book3-hardcover-v3-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/book3-hardcover-v3-1320w.webp",
        "w": 1320
      },
      {
        "src": "/covers/book3-hardcover-v3-2000w.webp",
        "w": 2000
      }
    ],
    "width": 2000
  },
  "/covers/book3-paperback.png": {
    "height": 1500,
    "variants": [
      {
        "src": "/covers/book3-paperback-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/book3-paperback-1000w.webp",
        "w": 1000
      }
    ],
    "width": 1000
  },
  "/covers/hawkes-ebook.jpg": {
    "height": 2400,
    "variants": [
      {
        "src": "/covers/hawkes-ebook-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/hawkes-ebook-1320w.webp",
        "w": 1320
      },
      {
        "src": "/covers/hawkes-ebook-1600w.webp",
        "w": 1600
      }
    ],
    "width": 1600
  },
  "/covers/hawkes-ebook.png": {
    "height": 3000,
    "variants": [
      {
        "src": "/covers/hawkes-ebook-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/hawkes-ebook-1320w.webp",
        "w": 1320
      },
      {
        "src": "/covers/hawkes-ebook-2000w.webp",
        "w": 2000
      }
    ],
    "width": 2000
  },
  "/covers/hawkes-hardcover-web.png": {
    "height": 3000,
    "variants": [
      {
        "src": "/covers/hawkes-hardcover-web-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/hawkes-hardcover-web-1320w.webp",
        "w": 1320
      },
      {
        "src": "/covers/hawkes-hardcover-web-2000w.webp",
        "w": 2000
      }
    ],
    "width": 2000
  },
  "/covers/hawkes-hardcover.png": {
    "height": 3075,
    "variants": [
      {
        "src": "/covers/hawkes-hardcover-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/hawkes-hardcover-1320w.webp",
        "w": 1320
      },
      {
        "src": "/covers/hawkes-hardcover-2000w.webp",
        "w": 2000
      }
    ],
    "width": 2050
  },
  "/covers/hawkes-paperback-web.png": {
    "height": 3000,
    "variants": [
      {
        "src": "/covers/hawkes-paperback-web-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/hawkes-paperback-web-1320w.webp",
        "w": 1320
      },
      {
        "src": "/covers/hawkes-paperback-web-2000w.webp",
        "w": 2000
      }
    ],
    "width": 2000
  },
  "/covers/hawkes-paperback.png": {
    "height": 2775,
    "variants": [
      {
        "src": "/covers/hawkes-paperback-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/hawkes-paperback-1320w.webp",
        "w": 1320
      },
      {
        "src": "/covers/hawkes-paperback-1850w.webp",
        "w": 1850
      }
    ],
    "width": 1850
  },
  "/covers/omnibus-case-cover.jpg": {
    "height": 3000,
    "variants": [
      {
        "src": "/covers/omnibus-case-cover-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/omnibus-case-cover-1320w.webp",
        "w": 1320
      },
      {
        "src": "/covers/omnibus-case-cover-2000w.webp",
        "w": 2000
      }
    ],
    "width": 2000
  },
  "/covers/omnibus-ebook.jpg": {
    "height": 2400,
    "variants": [
      {
        "src": "/covers/omnibus-ebook-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/omnibus-ebook-1320w.webp",
        "w": 1320
      },
      {
        "src": "/covers/omnibus-ebook-1600w.webp",
        "w": 1600
      }
    ],
    "width": 1600
  },
  "/covers/omnibus-hardcover-v3.png": {
    "height": 3000,
    "variants": [
      {
        "src": "/covers/omnibus-hardcover-v3-660w.webp",
        "w": 660
      },
      {
        "src": "/covers/omnibus-hardcover-v3-1320w.webp",
        "w": 1320
      },
      {
        "src": "/covers/omnibus-hardcover-v3-2000w.webp",
        "w": 2000
      }
    ],
    "width": 2000
  }
};
