# Batch configure email-mcp accounts from a local secrets file.
# Usage:
#   1. Copy email-mcp-secrets.example.txt → email-mcp-secrets.local.txt (same folder)
#   2. Fill in passwords (never commit .local.txt)
#   3. powershell -ExecutionPolicy Bypass -File scripts/batch_email_mcp_setup.ps1
#
# Or pass a custom path:
#   powershell -File scripts/batch_email_mcp_setup.ps1 -SecretsFile C:\path\to\secrets.txt

param(
    [string]$SecretsFile = (Join-Path $PSScriptRoot "email-mcp-secrets.local.txt")
)

$ErrorActionPreference = "Stop"
$configDir = Join-Path $env:USERPROFILE ".config\email-mcp"
$configPath = Join-Path $configDir "config.toml"

if (-not (Test-Path $SecretsFile)) {
    Write-Error "Secrets file not found: $SecretsFile`nCopy email-mcp-secrets.example.txt and fill it in."
}

function Parse-SecretsFile {
    param([string]$Path)
    $accounts = @()
    $current = $null
    foreach ($line in Get-Content $Path) {
        $t = $line.Trim()
        if ($t -eq "" -or $t.StartsWith("#")) { continue }
        if ($t -eq "---") {
            if ($null -ne $current -and $current.email -and $current.password) {
                $accounts += [PSCustomObject]$current
            }
            $current = @{ name = ""; email = ""; password = ""; imap_host = ""; imap_port = 993; smtp_host = ""; smtp_port = 465; provider = "" }
            continue
        }
        if ($t -match "^([^=]+)=(.*)$") {
            $key = $Matches[1].Trim().ToLower()
            $val = $Matches[2].Trim()
            if ($null -eq $current) {
                $current = @{ name = ""; email = ""; password = ""; imap_host = ""; imap_port = 993; smtp_host = ""; smtp_port = 465; provider = "" }
            }
            switch ($key) {
                "name"       { $current.name = $val }
                "email"      { $current.email = $val }
                "password"   { $current.password = ($val -replace '\s','') }
                "imap_host"  { $current.imap_host = $val }
                "imap_port"  { $current.imap_port = [int]$val }
                "smtp_host"  { $current.smtp_host = $val }
                "smtp_port"  { $current.smtp_port = [int]$val }
                "provider"   { $current.provider = $val }
            }
        }
    }
    if ($null -ne $current -and $current.email -and $current.password) {
        $accounts += [PSCustomObject]$current
    }
    return $accounts
}

function Get-GoogleDefaults {
    param([string]$Email)
    return @{
        imap_host = "imap.gmail.com"
        imap_port = 993
        smtp_host = "smtp.gmail.com"
        smtp_port = 465
    }
}

function Get-ProtonBridgeDefaults {
    return @{
        imap_host = "127.0.0.1"
        imap_port = 1143
        smtp_host = "127.0.0.1"
        smtp_port = 1025
    }
}

$accounts = Parse-SecretsFile -Path $SecretsFile
if ($accounts.Count -eq 0) {
    Write-Error "No accounts found in secrets file."
}

$lines = @(
    "# Generated by batch_email_mcp_setup.ps1 - $(Get-Date -Format 'yyyy-MM-dd HH:mm')",
    "",
    "[settings]",
    "rate_limit = 10",
    ""
)

foreach ($a in $accounts) {
    $name = if ($a.name) { $a.name } else { ($a.email -split "@")[0] -replace "[^a-z0-9]", "-" }
    $imapHost = $a.imap_host
    $imapPort = $a.imap_port
    $smtpHost = $a.smtp_host
    $smtpPort = $a.smtp_port

    if (-not $imapHost) {
        if ($a.email -like "*@protonmail.com" -or $a.email -like "*@proton.me") {
            $d = Get-ProtonBridgeDefaults
            $imapHost = $d.imap_host; $imapPort = $d.imap_port
            $smtpHost = $d.smtp_host; $smtpPort = $d.smtp_port
        } else {
            $d = Get-GoogleDefaults -Email $a.email
            $imapHost = $d.imap_host; $imapPort = $d.imap_port
            $smtpHost = $d.smtp_host; $smtpPort = $d.smtp_port
        }
    }

    $lines += "[[accounts]]"
    $lines += "name = `"$name`""
    $lines += "email = `"$($a.email)`""
    $lines += "full_name = `"Jason Carroll Holloway`""
    $lines += "password = `"$($a.password)`""
    $lines += ""
    $isProton = ($a.provider -eq "proton-bridge") -or ($a.email -like "*@protonmail.com") -or ($a.email -like "*@proton.me")

    $lines += "[accounts.imap]"
    $lines += "host = `"$imapHost`""
    $lines += "port = $imapPort"
    if ($isProton) {
        $lines += "tls = false"
        $lines += "starttls = true"
        $lines += "verify_ssl = false"
    } else {
        $lines += "tls = true"
        $lines += "verify_ssl = false"
    }
    $lines += ""
    $lines += "[accounts.smtp]"
    $lines += "host = `"$smtpHost`""
    $lines += "port = $smtpPort"
    if ($isProton) {
        $lines += "tls = false"
        $lines += "starttls = true"
        $lines += "verify_ssl = false"
    } else {
        $lines += "tls = true"
        $lines += "starttls = false"
        $lines += "verify_ssl = false"
    }
    $lines += ""
}

New-Item -ItemType Directory -Force -Path $configDir | Out-Null
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($configPath, ($lines -join "`n"), $utf8NoBom)

Write-Host "Wrote $($accounts.Count) account(s) to $configPath"
Write-Host "Testing connections..."
& npx -y @codefuturist/email-mcp test 2>&1
Write-Host "Done. Restart Cursor to load the email MCP server."
